<?php

namespace common\helpers;

/**
 * Created by PhpStorm.
 * User: lengbin
 * Date: 2017/2/2
 * Time: 下午4:57
 */
class ConstantHelper
{
    // cache
    CONST COMMON_CACHE_DI = '_common_cache_di';
    CONST COMMON_CACHE_EVENT = '_common_cache_event';
    // cache

    // 没有删除
    CONST NOT_DELETE = 0;

    CONST BROWSER_TYPE_CHROME = 1;
    CONST BROWSER_TYPE_FIREFOX = 2;
    CONST BROWSER_TYPE_IE = 3;

    CONST TEST_ITEM_TYPE_HREF = 1;
    CONST TEST_ITEM_TYPE_PAGE = 2;

    CONST TEST_CASE_EVENT_TYPE_INPUT = 1;
    CONST TEST_CASE_EVENT_TYPE_CLIENT = 2;
    CONST TEST_CASE_EVENT_TYPE_SELECT = 3;
    CONST TEST_CASE_EVENT_TYPE_CHECKBOX = 4;
    CONST TEST_CASE_EVENT_TYPE_FILE = 5;
    CONST TEST_CASE_EVENT_TYPE_WAIT = 6;

    CONST TEST_CASE_FIND_ELEMENT_TYPE_ID = 1;
    CONST TEST_CASE_FIND_ELEMENT_TYPE_XPATH = 2;
    CONST TEST_CASE_FIND_ELEMENT_TYPE_CLASS = 3;
    CONST TEST_CASE_FIND_ELEMENT_TYPE_CSS = 4;
    CONST TEST_CASE_FIND_ELEMENT_TYPE_NAME = 5;
    CONST TEST_CASE_FIND_ELEMENT_TYPE_LINK = 6;

    CONST TEST_ACCEPT_TYPE_STRING_SEE = 1;
    CONST TEST_ACCEPT_TYPE_STRING_NOT_SEE = 2;
    CONST TEST_ACCEPT_TYPE_CHECK_CHECKED = 3;
    CONST TEST_ACCEPT_TYPE_CHECK_NOT_CHECKED= 4;
    CONST TEST_ACCEPT_TYPE_CHECKBOX_CHECKED = 5;
    CONST TEST_ACCEPT_TYPE_CHECKBOX_NOT_CHECKED = 6;
    CONST TEST_ACCEPT_TYPE_SELECT_SELECTED = 7;
    CONST TEST_ACCEPT_TYPE_SELECT_NOT_SELECTED = 8;
    CONST TEST_ACCEPT_TYPE_URL_EQUAL = 9;
    CONST TEST_ACCEPT_TYPE_URL_NOT_EQUAL = 10;
    CONST TEST_ACCEPT_TYPE_URL_MATCH = 11;
    CONST TEST_ACCEPT_TYPE_URL_NOT_MATCH = 12;
    CONST TEST_ACCEPT_TYPE_CURRENT_URL_IN = 13;
    CONST TEST_ACCEPT_TYPE_CURRENT_URL_NOT_IN = 14;
    CONST TEST_ACCEPT_TYPE_ELEMENT_SEE = 15;
    CONST TEST_ACCEPT_TYPE_ELEMENT_NOT_SEE = 16;
    CONST TEST_ACCEPT_TYPE_SOURCE_IN = 17;
    CONST TEST_ACCEPT_TYPE_SOURCE_NOT_IN = 18;
    CONST TEST_ACCEPT_TYPE_LINK_SEE = 19;
    CONST TEST_ACCEPT_TYPE_LINK_NOT_SEE = 20;


}